#Requires -RunAsAdministrator
param([Parameter(Mandatory)][string]$CampaignId,[string]$VMName='Evidence1-Runner-E2E',[string]$ExpectedVMId='fd7c0298-186f-4a8e-9ae8-0a8af6969d14',[Parameter(Mandatory)][string]$OutDir)
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
Import-Module (Join-Path $PSScriptRoot 'evidence1-final-codex-host-contract.psm1') -Force -DisableNameChecking
if($CampaignId-cnotmatch'^[0-9a-f]{8}-(?:[0-9a-f]{4}-){3}[0-9a-f]{12}$'){throw 'campaign_id_invalid'}
$expected="C:\kmp-eval\scratch\evidence1-final-codex-failure-diagnostics\$CampaignId"
if(-not([IO.Path]::GetFullPath($OutDir).Equals($expected,[StringComparison]::OrdinalIgnoreCase))-or(Test-Path -LiteralPath $OutDir)){throw 'diagnostic_destination_invalid'}
$vm=Get-VM -Name $VMName -ErrorAction Stop;if(([string]$vm.Id).ToLowerInvariant()-cne$ExpectedVMId.ToLowerInvariant()-or[string]$vm.State-cne'Off'){throw 'exact_vm_must_be_off'}
$disk=(Get-VMHardDiskDrive -VMName $VMName|Select-Object -First 1).Path;$mount=$null
try{$mount=Mount-VHD -Path $disk -ReadOnly -Passthru -ErrorAction Stop;$root=Get-E1FinalMountedWindowsRoot $mount;$ops=Join-Path $root 'Evidence1Ops\final-codex';$terminal=Join-Path $ops "$CampaignId.terminal.json";if(-not(Test-Path -LiteralPath $terminal -PathType Leaf)){throw 'terminal_missing'};$value=Get-Content -LiteralPath $terminal -Raw|ConvertFrom-Json -ErrorAction Stop;if($value.state-cne'failed'){throw 'campaign_not_failed'};New-Item -ItemType Directory -Path $OutDir -ErrorAction Stop|Out-Null
foreach($pair in @(@{source=$terminal;name='terminal.json'},@{source=(Join-Path $ops "$CampaignId.terminal.claim.json");name='terminal.claim.json'},@{source=(Join-Path $ops "$CampaignId.stdout.log");name='wrapper.stdout.log'},@{source=(Join-Path $ops "$CampaignId.stderr.log");name='wrapper.stderr.log'})){if(Test-Path -LiteralPath $pair.source -PathType Leaf){Copy-Item -LiteralPath $pair.source -Destination (Join-Path $OutDir $pair.name) -ErrorAction Stop}}
[IO.File]::WriteAllText((Join-Path $OutDir 'diagnostic.json'),([ordered]@{schema=1;verdict='PASS';campaign_id=$CampaignId;terminal_state=[string]$value.state;terminal_reason_code=[string]$value.reason_code;retry_count=[int]$value.retry_count;provider_sessions_consumed=0;raw_provider_content_read=$false;generated_at_utc=[datetime]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ss.fffZ')}|ConvertTo-Json -Compress),[Text.UTF8Encoding]::new($false));Write-Host "[evidence1-copy-final-codex-failure-diagnostic] PASS: $OutDir"}finally{if($mount){Dismount-VHD -Path $disk -ErrorAction SilentlyContinue}}
